package:
  name: idvc
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

  preserve_egg_dir: False

  entry_points:
    - idvc = idvc.dvc_interface:main

  missing_dso_whitelist:
    - /lib64/libc.so.6            # [linux]
    - /lib64/libm.so.6            # [linux]
    - /lib64/libpthread.so.0      # [linux]
    - /lib64/ld-linux-x86-64.so.2 # [linux]
    - C:\Windows\System32\ADVAPI32.dll # [win]
    - C:\Windows\System32\KERNEL32.dll # [win]
    - C:\Windows\System32\msvcrt.dll   # [win]
    - C:\Windows\System32\SHELL32.dll  # [win]


test:
  source_files:
    - ./test

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover test
  
requirements:
  
  build:
    - python 
    - openmp                # [osx]
    - cmake
    - numpy {{ numpy }}

  run:
    - python
    - numpy
    - ccpi-viewer >=21.1.1
    - ccpi-dvc >=21.1.0
    - natsort
    - docopt
    - matplotlib
    - openmp                # [osx]
    - qdarkstyle
    - importlib_metadata    # [py<38]

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Digital Volume Correlation GUI'
