package:
  name: ccpi-dvc-gui
  version: 21.0.1

build:
  preserve_egg_dir: False
  

  entry_points:
    - idvc = ccpi.dvc.apps.dvc_interface:main
  number: 0
  
requirements:
  build:
    - python 
    - openmp # [osx]
    - cmake
    - numpy {{ numpy }} 
    
 
  run:
    - python
    - numpy
    - ccpi-viewer >=21.0.1
    - ccpi-dvc >=21.0.0
    - natsort
    - docopt
    - matplotlib
    - openmp # [osx]
    - qdarkstyle
    

    

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Digital Volume Correlation GUI'
