package:
  name: ccpi-dvc-gui
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

  preserve_egg_dir: False

  entry_points:
    - idvc = ccpi.dvc.apps.dvc_interface:main
test:
  source_files:
    - ./Wrappers/Python/test # [win]
    - ./ccpi/test # [not win]
  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover Wrappers/Python/test # [win]
    - python -m unittest discover -s ccpi/test # [not win]
    
requirements:
  build:
    - python 
    - openmp # [osx]
    - cmake
    - numpy {{ numpy }} 

  run:
    - python
    - numpy
    - ccpi-viewer >=21.0.1
    - ccpi-dvc >=21.0.0
    - natsort
    - docopt
    - matplotlib
    - openmp # [osx]
    - qdarkstyle

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Digital Volume Correlation GUI'
