name: conda_build
on:
  release:
    types: [published]
  push:
    branches: [master]
    tags: ['**']
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: publish-to-conda
      uses: TomographicImaging/conda-package-publish-action@v2
      with:
        subDir: 'recipe'
        channels: '-c conda-forge -c ccpi'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        test_all: ${{(github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || (github.ref == 'refs/heads/master')}}
        convert_win: false
        convert_osx: false
        test_pyver: 3.9
        test_npver: 1.22
